# Generated by Django 3.1.4 on 2021-04-30 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('contactno', models.BigIntegerField(default=0, unique=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('active', models.CharField(max_length=100, null=True)),
                ('lastlogin', models.CharField(max_length=100, null=True)),
                ('auth_key', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('contactno', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.admin')),
            ],
        ),
        migrations.CreateModel(
            name='yelpshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(max_length=100, null=True)),
                ('mapurl', models.CharField(max_length=500, null=True)),
                ('last_fetchid', models.CharField(max_length=100, null=True)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.shop')),
            ],
        ),
        migrations.CreateModel(
            name='shopaspectarchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspectname', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.admin')),
            ],
        ),
        migrations.CreateModel(
            name='reviewdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeofreview', models.CharField(max_length=20, null=True)),
                ('review', models.CharField(max_length=2000, null=True)),
                ('sentiment', models.FloatField(null=True)),
                ('isaspectdone', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(default='noname', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('reviewid', models.CharField(max_length=40, null=True)),
                ('timestamp', models.CharField(max_length=40, null=True)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.shop')),
            ],
        ),
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspectrequest', models.IntegerField(default=0)),
                ('sentimentrequest', models.IntegerField(default=0)),
                ('googlerequest', models.IntegerField(default=0)),
                ('yelprequest', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('shop_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.shop')),
            ],
        ),
        migrations.CreateModel(
            name='googleshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(max_length=100, null=True)),
                ('mapurl', models.CharField(max_length=500, null=True)),
                ('last_fetchid', models.CharField(max_length=100, null=True)),
                ('shop_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.shop')),
            ],
        ),
        migrations.CreateModel(
            name='fbshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(max_length=100, null=True)),
                ('fb_page_url', models.CharField(max_length=500, null=True)),
                ('total_review_count', models.IntegerField(default=0)),
                ('shop_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.shop')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100, null=True)),
                ('total_aspect', models.IntegerField(null=True)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.shop')),
            ],
        ),
        migrations.CreateModel(
            name='aspectdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(max_length=500, null=True)),
                ('sentiment', models.FloatField(null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.category')),
                ('reviewdata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedclientpanel.reviewdata')),
            ],
        ),
    ]
